name: Refresh Pipeline (Clean-v2)

on:
  workflow_dispatch:
    inputs:
      limit:
        description: 'Maximum titles to process'
        required: true
        default: '10000'
        type: string
      filter:
        description: 'Filter by type'
        required: false
        default: 'both'
        type: choice
        options:
          - both
          - movies-only
          - tv-only
      offset:
        description: 'Skip first n titles'
        required: false
        default: '0'
        type: string
      resume:
        description: 'Resume from checkpoint'
        required: false
        default: false
        type: boolean

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 360  # 6 hour max

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run refresh pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          TMDB_TOKEN: ${{ secrets.TMDB_TOKEN }}
        run: |
          echo "Starting refresh pipeline..."
          echo "Limit: ${{ inputs.limit }}"
          echo "Filter: ${{ inputs.filter }}"
          echo "Offset: ${{ inputs.offset }}"
          echo "Resume: ${{ inputs.resume }}"

          # Build command
          CMD="node clean-v2/pipelines/refresh-pipeline.js --limit ${{ inputs.limit }}"

          # Add offset if specified
          if [ "${{ inputs.offset }}" != "0" ]; then
            CMD="$CMD --offset ${{ inputs.offset }}"
          fi

          # Add filter if specified
          if [ "${{ inputs.filter }}" = "movies-only" ]; then
            CMD="$CMD --movies-only"
          elif [ "${{ inputs.filter }}" = "tv-only" ]; then
            CMD="$CMD --tv-only"
          fi

          # Add resume if specified
          if [ "${{ inputs.resume }}" = "true" ]; then
            CMD="$CMD --resume"
          fi

          # Run the command
          $CMD

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: refresh-logs
          path: |
            clean-v2/logs/*.log
            clean-v2/logs/*.json
          retention-days: 7
